### ISSUE TITLE
Errors due to null audio context on Safari

### ISSUE THREAD

**Issue by bflora2** [goldfire/howler.js#1063]
I receive frequent Howler error reports from the field with error message: **null is not an object (evaluating 'n.ctx.createGain')**. The error is thrown while calling the Howler constructor. I'm using howler.core.min.js version 2.0.15. The sound source is an MP3 file. The error only occurs in the Safari browser for both Mac OS and iOS. Safari versions 10, 11, and 12 are all affected.

In howler.js (v2.0.15), `ctx.createGain` only appears on lines 2058 and 2307, and there doesn't appear to be a check for a null `ctx` before referencing `ctx.createGain` at either line. I just enabled error reporting on the Howler code today, so I don't know how long the issue has existed. I receive about a half dozen of these reports per hour, but only a small minority of Safari users seem to be affected. I don't see the error on my Mac or my iPad.

**Comment by LaCollision** [comment]
Hi,
Exact same error here on multiple Macs and multiple Safari versions.

The sounds can't be played after this error - that's a real issue here.

**Comment by goldfire** [comment]
This should now be fixed with https://github.com/goldfire/howler.js/commit/758358e3e73efd91ade59a83908bb60e02802cd2.

**Comment by AndyMillne** [comment]
The fix seems to have moved the error elsewhere.

![image](https://user-images.githubusercontent.com/39617226/54018212-5a6d9700-4188-11e9-88bf-6588db3f6a86.png)

Still affecting Safari on Mac and iOS

**Comment by alexwenbj** [comment]
Yes,This problem still exists in safari.Especially when you play sound server times.
